[PTP-44] Get summary length of all interviews and remove invalid data
michalbaldyga/personality-type-prediction-ops pull request #17
Opened 2023-11-23 19:19 UTC by jakubantoszek

Result was 1278 hours of interviews

2023-11-23 21:08 UTC, michalbaldyga requested changes
Poza tym "elo" wszystko pięknie, tylko można jeszcze dodać komentarze do funkcji

2023-11-23 21:08 UTC, michalbaldyga commented on backend/gathering_data/get_interviews_time.py
> +                    raise Exception("elo")
Uprasza się o nie rzucanie wyjątków o treści "elo".

2023-11-25 13:51 UTC, BaranskiKacper approved these changes

2023-11-25 13:52 UTC, BaranskiKacper approved these changes

2023-11-25 13:54 UTC, michalbaldyga approved these changes

2023-11-25 15:49 UTC, merged