[PTP-56] Dostosować frontend do Ruffa
michalbaldyga/personality-type-prediction-ops pull request #19
Opened 2023-11-24 22:52 UTC by AgnieszkaDelmaczynska

2023-11-25 13:32 UTC, BaranskiKacper commented on frontend/src/chart_frame.py
> +        """Create a bar chart and display it in the Tkinter window.
Generalnie dobrze, ale zmień proszę format komentarzy na analogiczny do tego:

   ```
 """Flatten a nested dictionary by concatenating parent and child keys.

    Parameters:
    nested_dict (dict): A nested dictionary with dictionaries as values.

    Returns:
    dict: A flattened dictionary with concatenated keys.
    """
```

Chodzi oto żebyśmy wszyscy trzymali się jednego schematu

2023-11-25 13:37 UTC, BaranskiKacper commented on frontend/src/predict_frame.py
> +        """Initialize the PredictFrame.
Tu już masz inny format. Trzymajmy się jednego dla czytelności

2023-11-25 13:38 UTC, BaranskiKacper requested changes
Popraw komenatrze i będzie można wrzucać

2023-11-25 13:39 UTC, michalbaldyga commented on frontend/src/chart_frame.py
> +        """Create a bar chart and display it in the Tkinter window.
Trzeba ustalić z jakiego schematu korzystamy, bo ja np. stosowałem ten:
```python
    """Convert seconds to milliseconds.

    :param seconds: float, time in seconds
    :return: int, equivalent time in milliseconds
    """
```

2023-11-25 13:59 UTC, BaranskiKacper commented on frontend/src/chart_frame.py
> +        """Create a bar chart and display it in the Tkinter window.
To jednak bierzemy ten co Michał dał. Ja też zmienie u siebie to

2023-11-26 16:09 UTC, AgnieszkaDelmaczynska commented on frontend/src/chart_frame.py
> +        """Create a bar chart and display it in the Tkinter window.
Ok, poprawię

2023-11-26 16:11 UTC, AgnieszkaDelmaczynska commented
Wprowadziłam zmiany @BaranskiKacper @michalbaldyga

2023-11-26 16:15 UTC, BaranskiKacper approved these changes

2023-11-26 16:17 UTC, merged